apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeks.argo.discover.upbound.io
spec:
  group: argo.discover.upbound.io
  names:
    kind: XEKS
    plural: xeks
  claimNames:
    kind: EKS
    plural: eks
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              awsAccountId:
                type: string
              argoRoleArn:
                type: string
              assumeRoleArn:
                type: string
              assumeRoleWithWebIdentityArn:
                type: string
              region:
                type: string
              search:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
            required:
            - argoRoleArn
            - awsAccountId
            - region
            - search
          status:
            description: A Status represents the observed state
            properties:
              status:
                description: Freeform field containing status information for eks
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
